### ISSUE TITLE
Unsupported nuget variables?

### ISSUE THREAD

**Issue by The-Futurist** [deadlydog/New-NuGetPackage#10]
I get build warnings when I build  like:

- Author was not specified. Using 'Mike'
- Description was not specified. Using 'Description'

I tried adding stuff to the .ps1 file $author that had no effect, then $authors that too had no effect, nor does $description.

I also tried setting the AssemblyDescription in the AssemblyInfo.cs file but again no effect.

**Comment by deadlydog** [comment]
Hey @Korporal, are you using a .nuspec file? If so, you can use the `$author$` and `$description$` keywords in your nuspec file to pull the values from AssemblyInfo.cs, or you can hardcode those values in the nuspec file if you prefer.

If you don't have a nuspec file defined, then it should just use whatever values you have defined in your AssemblyInfo.cs file. By default I don't believe the `Company` or `Description` fields are populated, so you would need to update those.

The `Config.ps1` script does not support any variables that are not already defined in it, so you adding a `$author` variable to that script will have no effect.

Let me know if that gets you going or not. Thanks.

**Comment by deadlydog** [comment]
No response so closing this one.
