### ISSUE TITLE
Include resource files

### ISSUE THREAD

**Issue by rehm-schneider** [deadlydog/New-NuGetPackage#11]
I'm not sure if this is the correct spot to bring this up, but my packages that are created using CreateNewNuGetPackageAfterEachProjectBuild are missing the project's resource files. Is there a possibility to include them automatically?

**Comment by deadlydog** [comment]
You'll likely need to use a .nuspec file to make that happen. Check out NuGet's documentation for more info.

https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package 
https://docs.microsoft.com/en-us/nuget/reference/nuspec

Hopefully that helps and gets you going.

**Comment by deadlydog** [comment]
No response so closing this one.
