### ISSUE TITLE
How do I include a generated documentation XML file into the generated package?

### ISSUE THREAD

**Issue by The-Futurist** [deadlydog/New-NuGetPackage#15]
@deadlydog 
Is there a way?

**Comment by deadlydog** [comment]
Yes. You'll need to use an explicit .nuspec file in your project, and tell it to include the .xml file.

e.g. Something like this:
```
  <files>
    <file src="bin\$configuration$\$id$.*" target="lib\net452\" />
  </files>
```
or
```
  <files>
    <file src="bin\$configuration$\Name.Of.Your.Project.*" target="lib\net452\" />
  </files>
```

For more info about the .nuspec file and it's syntax, see [the official docs](https://docs.microsoft.com/en-us/nuget/reference/nuspec).

**Comment by The-Futurist** [comment]
@deadlydog - Thanks !

**Comment by deadlydog** [comment]
No problem :) I'm going to close this one off.
