### ISSUE TITLE
Pack with nuspec instead of csproj

### ISSUE THREAD

**Issue by kassiokiarelly** [deadlydog/New-NuGetPackage#16]
Hello!

I installed the https://www.nuget.org/packages/CreateNewNuGetPackageFromProjectAfterEachBuild/
nuget package in my project and want to prevent the output exe to be added as a reference in project the install my nupkg.

To acomplish that i need to pack with nuspec instead of csproj and couldn't find how to do that in the documentation. Anyone knows how to?

**Comment by deadlydog** [comment]
Hey @kassiokiarelly if you include a .nuspec file in your project, it should get picked up and used automatically.

**Comment by deadlydog** [comment]
I'm going to assume my answer above answered the question. Closing this issue.
