### ISSUE TITLE
how to add a 'readme.txt' file

### ISSUE THREAD

**Issue by ribsdigital** [deadlydog/New-NuGetPackage#17]
hey there,

i've been using the project now for a while and it's tip top ;)

one thing that's escaping me though is how to included a 'readme.txt' file in the resulting nuget package that's created when building the project and have that file open in vs once the package has been installed...

i've tried adding this to the nuspec file:

```
<files>
	<file src="readme.txt" target="" />
</files>
```
where the 'readme.txt' file is at the same level as the nuspec and csproj file and although it seems to put the file at the root level of the package, it installs it into the directory structure rather than just opening it...

what am i missing... any suggestions would amazin!

**Comment by deadlydog** [comment]
Hey @ribsdigital this isn't really an issue with this New-NuGetPackage project, but rather a general NuGet issues (you'd need to solve it even when not using New-NuGetPackage). I believe you'll need to leverage an install.ps1 tools script in your NuGet package to display the ReadMe.txt, as shown in [this blog post](https://weblog.west-wind.com/posts/2018/Jan/29/Distributing-Content-and-Showing-a-ReadMe-file-in-a-NET-Core-Nuget-Package).

If you need further help, I'd recommend checking the nuspec docs for `tools` and `install.ps1`, or asking on stackoverflow.com, as I'm sure others in the community have done it and could provide more guidance.
