### ISSUE TITLE
Output file name package includes configuration and platform

### ISSUE THREAD

**Issue by davidcon** [deadlydog/New-NuGetPackage#19]
This project is an excelent tool. 
I have a little problem with the output file name when I build a release, in the console appears:

`Successfully created package 'packagePath\NameProject.3.0.7706.22372.nupkg'.
5>  DETALLADO: Performing any required New-NuGetPackage script cleanup...
5>  DETALLADO: New-NuGetPackage script finished running at 12:25:54.4864894. Completed in 5,151172 seconds.
5>  'packagePath\NameProject.3.0.7706.22372.nupkg' was renamed to 'packagePath\NameProject.3.0.7706.22372.Release.AnyCPU.nupkg'.
5> packagePath\NameProject.3.0.7706.22372.Release.AnyCPU.nupkg`

Do you know how to avoid this renamed? 
If the package name include "Release.AnyCPU" then when I try to install it fails.

Thank you very much!

**Comment by deadlydog** [comment]
Yup, in [your Config.ps1 file](https://github.com/deadlydog/New-NuGetPackage/blob/566127ce6fc2dacedff52e85dad109497a62fba3/tools/CreateNewNuGetPackageFromProjectAfterEachBuild%20NuGet%20Package/Content/Config.ps1#L50) you should be able to simply set the following variable to false to prevent it from renaming the nuget package:

```powershell
$appendConfigurationAndPlatformToNuGetPackageFileName = $false
```

**Comment by davidcon** [comment]
@deadlydog thank you very much. Very easy if you read the configuration file ;-)

This time I have read "Config.ps1" fully, do you know if is there any way to relocate all .nupkg files in a subdirectory inside release folder? 

Thank you very much!

**Comment by deadlydog** [comment]
No, it will currently always create the .nupkg file in the project's output directory. I believe you would need to write a separate post-build script to find and move all .nupkg files, or some other custom solution.

**Comment by davidcon** [comment]
@deadlydog thank you very much. I will follow your advise and I will generate a post-build script. Great proyect!!
I have changed the post-build like this (change is in bold):
PowerShell -NoProfile -ExecutionPolicy Bypass -Command "& '$(ProjectDir)_CreateNewNuGetPackage\DoNotModify\CreateNuGetPackage.ps1' -ProjectFilePath '$(ProjectPath)' -OutputDirectory '$(TargetDir)**\MyNugetDirectory**' -BuildConfiguration '$(ConfigurationName)' -BuildPlatform '$(PlatformName)'
